version: '3.0'

volumes:
    mysql-volume:
    pma-session-store:

services:
    app:
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        volumes:
            - ./laravel/:/var/www/html
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=${DB_NAME}
            - DB_USERNAME=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
    web:
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        ports:
            - ${WEB_PORT}:80
        depends_on:
            - app
        volumes:
            - ./laravel:/var/www/html
    db:
        build:
            context: .
            dockerfile: ./docker/db/Dockerfile
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            TZ: 'Asia/Tokyo'
        volumes:
            - mysql-volume:/var/lib/mysql
    pma:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=db
            - PMA_USER=db_user
            - PMA_PASSWORD=db_password
        ports:
            - 8080:80
        volumes:
            - pma-session-store:/sessions